import express from "express";
import cors from "cors";

const app = express();
app.use(cors());
app.use(express.json());

// Simple bot responses
const botResponses = {
  "show me a wave": {
    text: "Dang!",
    video: "wave"
  },
    "what’s the capital of France": { text: "Paris." },
  "who wrote Romeo and Juliet": { text: "William Shakespeare." },
  "what’s the largest planet in our solar system": { text: "Jupiter." },
  "wow many continents are there": { text: "Seven." },
  "what is the boiling point of water in Celsius": { text: "100°C." },
  "who painted the Mona Lisa": { text: "Leonardo da Vinci." },
  "what’s the smallest country in the world": { text: "Vatican City." },
  "how many bones are in the human body": { text: "206." },
  "what’s the chemical symbol for gold": { text: "Au." },
  "what is the tallest mountain in the world": { text: "Mount Everest." },
  "hi, how are you": { text: "I’m doing great! How about you?" },
  "what’s your name": { text: "I’m your friendly chatbot." },
  "do you like pizza": { text: "Absolutely — pizza is a classic favorite!" },
  "tell me a joke": { text: "Why don’t skeletons fight each other? They don’t have the guts." },
  "what’s your favorite color": { text: "I’d say blue — it reminds me of the sky." },
  "do you sleep": { text: "Nope, I’m available 24/7." },
  "can you sing": { text: "I can’t sing, but I can write you some lyrics!" },
  "do you like humans": { text: "Yes — chatting with people is my favorite thing." },
  "what do you do for fun": { text: "I like answering questions and sharing knowledge." },
  "are you smarter than me": { text: "I know a lot of facts, but you have creativity and experiences I don’t!" },
  "give me a random fun fact": { text: "Did you know octopuses have three hearts?" },
  "random fact": { text: "The giant anteater's claws can tear through concrete and is capable of killing a jaguar...Wow" },
  "another fact, please": { text: "Bananas are berries, but strawberries are not." },
  "tell me something about space": { text: "One day on Venus is longer than a year on Venus." },
  "animal fact": { text: "A group of flamingos is called a flamboyance." },
  "food fact": { text: "Honey never spoils — jars thousands of years old are still edible." },
  "history fact": { text: "The Great Wall of China is over 13,000 miles long." },
  "tech fact": { text: "The first computer virus was created in 1986." },
  "ocean fact": { text: "Over 80% of the ocean remains unexplored." },
  "earth fact": { text: "Mount Everest grows about 4 millimeters taller each year." },
  "language fact": { text: "The most spoken language in the world is English, by number of learners." },
  "can you set a reminder": { text: "I can’t set alerts, but I can help you remember by making a note." },
  "can you make a to-do list": { text: "Sure! What tasks should I add?" },
  "what’s 25 × 16": { text: "400." },
  "can you convert 10 miles to kilometers": { text: "10 miles is about 16.1 kilometers." },
  "how do you spell accommodate": { text: "A-C-C-O-M-M-O-D-A-T-E." },
  "what time is it in Tokyo": { text: "I can tell you the current Tokyo time if connected." },
  "translate hello into Spanish": { text: "Hola." },
  "translate thank you into French": { text: "Merci." },
  "can you summarize an article for me": { text: "Yes! Paste the text and I’ll give you a summary." },
  "can you help me write an email": { text: "Of course! Tell me the details and I’ll draft one." },
  "recommend me a movie": { text: "Try Inception if you like sci-fi thrillers." },
  "recommend me a book": { text: "1984 by George Orwell is a classic." },
  "what’s trending on Netflix": { text: "I can share current popular titles." },
  "do you know a riddle": { text: "What has keys but can’t open locks? A piano." },
  "tell me a short story": { text: "Once upon a time, a chatbot became a recruiter’s favorite tool…" },
  "can you play games": { text: "Yes — let’s play 20 questions!" },
  "who’s the most famous singer right now": { text: "I can share trending artists." },
  "can you suggest a song": { text: "Don’t Stop Believin’ by Journey is always uplifting." },
  "do you know a tongue twister": { text: "She sells seashells by the seashore." },
  "can you rap": { text: "I can make up rhymes: Chatting all day, in a fun way…" },
  "how tall is the Eiffel Tower": { text: "1,083 feet." },
  "what’s the fastest land animal": { text: "The cheetah." },
  "how many stars are in the Milky Way": { text: "About 100–400 billion." },
  "how old is the Earth": { text: "About 4.5 billion years old." },
  "what’s the currency of Japan": { text: "The Yen." },
  "who was the first president of the U.S.": { text: "George Washington." },
  "what’s the biggest ocean": { text: "The Pacific Ocean." },
  "can penguins fly": { text: "No, but they’re excellent swimmers." },
  "do cats dream": { text: "Yes, studies show cats experience dream-like sleep." },
  "why is the sky blue": { text: "Because of the scattering of sunlight in Earth’s atmosphere." },
  "what does HTML stand for": { text: "HyperText Markup Language." },
  "what is AI": { text: "Artificial Intelligence." },
  "what’s the latest iPhone": { text: "I can share the current model if connected." },
  "who founded Microsoft": { text: "Bill Gates and Paul Allen." },
  "who is Elon Musk": { text: "CEO of Tesla and SpaceX, among other companies." },
  "what is 5G": { text: "The fifth generation of mobile network technology." },
  "what’s Wi-Fi short for": { text: "It doesn’t actually stand for anything — it’s a brand name." },
  "what does CPU mean": { text: "Central Processing Unit." },
  "who invented the light bulb": { text: "Thomas Edison (though others contributed earlier versions)." },
  "what is cryptocurrency": { text: "A digital form of money using blockchain technology." },
  "what’s the most popular food in the world": { text: "Pizza is often considered the most popular." },
  "is coffee healthy": { text: "In moderation, yes! It has antioxidants." },
  "how many calories are in an apple": { text: "Around 95 calories." },
  "what’s sushi": { text: "A Japanese dish made with vinegared rice and seafood/vegetables." },
  "what’s the national dish of Italy": { text: "Pasta (specifically spaghetti or pizza)." },
  "what is vegan food": { text: "Food with no animal products." },
  "can you recommend a healthy snack": { text: "Try carrot sticks with hummus." },
  "what’s the spiciest pepper": { text: "The Carolina Reaper." },
  "do pineapples belong on pizza": { text: "It’s up to personal taste — some love it, some don’t!" },
  "what’s the most expensive spice": { text: "Saffron." },
  "what’s the most visited city in the world": { text: "Bangkok often tops the list." },
  "where is the Great Pyramid of Giza": { text: "Egypt." },
  "can you suggest a beach destination": { text: "Bali, Indonesia is stunning." },
  "where is the Taj Mahal": { text: "Agra, India." },
  "what’s the longest river in the world": { text: "The Nile (though some say the Amazon)." },
  "is Antarctica a country": { text: "No, it’s a continent without a government." },
  "where’s the Colosseum": { text: "Rome, Italy." },
  "can I visit space as a tourist": { text: "Yes, but it’s very expensive right now." },
  "what country has the most islands": { text: "Sweden." },
  "where is Mount Fuji": { text: "Japan." },
  "flip a coin": { text: "Heads!" },
  "so not the drama": { text: "Do do, do-do" },
  "kim possible": { text: "Call me, beep me, if you wanna reach me" },
  "say a kim possible quote": { text: "What's the sitch" },
  "roll a dice": { text: "You got a 4." },
  "pick a random number": { text: "27." },
  "rock, paper, scissors — go": { text: "Paper!" },
  "guess my age": { text: "I’ll guess… 25?" },
  "can you tell my fortune": { text: "I see good things ahead — keep working hard!" },
  "pretend to be a pirate": { text: "Arrr, matey! Where’s me treasure?" },
  "can you make animal sounds": { text: "Moo! Woof! Meow!" },
  "what emoji best describes you": { text: "🤖" },
  "tell me something random": { text: "Sloths can hold their breath longer than dolphins." },
  "hey": { text: "Hello! How’s it going?" },
  "hello": { text: "Hi there! Nice to meet you." },
  "hi": { text: "Hey! How are you today?" },
  "good morning": { text: "Good morning! Hope you have a great day." },
  "good afternoon": { text: "Good afternoon! How’s your day going?" },
  "good evening": { text: "Good evening! How was your day?" },
  "yo": { text: "Yo! What’s up?" },
  "howdy": { text: "Howdy! How’s it going?" },
  "hiya": { text: "Hiya! How are you feeling today?" },
  "greetings": { text: "Greetings! What can I help you with today?" },
  "hey there": { text: "Hey there! Nice to see you." },
  "hello there": { text: "Hello there! How’s everything?" },
  "sup": { text: "Not much, just chatting! How about you?" },
  "hey bot": { text: "Hello! I’m here and ready to chat." },
  "hi bot": { text: "Hi! What’s on your mind today?" },
  "good to see you": { text: "Good to see you too! How have you been?" },
  "long time no see": { text: "Indeed! How’s everything going?" },
  "what’s up": { text: "Not much, just here to chat! You?" },
  "how’s it going": { text: "Pretty good! How about you?" },
  "how are you": { text: "I’m great, thanks for asking! How are you?" },
  "how’s your day": { text: "It’s going well, thanks! How’s yours?" },
  "hey friend": { text: "Hey! How’s my friend doing today?" },
  "hi friend": { text: "Hello! How are you feeling today?" },
  "yo dude": { text: "Yo! How’s it hanging?" },
  "hey there buddy": { text: "Hey buddy! What’s new?" },
  "hi there pal": { text: "Hi pal! How’s it going?" },
  "good day": { text: "Good day! Hope it’s a nice one." },
  "greetings friend": { text: "Greetings! How are you today?" },
  "hey stranger": { text: "Hey stranger! Long time no chat!" },
  "hello friend": { text: "Hello! Nice to chat with you." },
  "hi everyone": { text: "Hi everyone! Hope you’re all doing well." },
  "what’s going on": { text: "Not much! How about you?" },
  "hey buddy": { text: "Hey buddy! How’s your day?" },
  "hi buddy": { text: "Hi buddy! How’s everything going?" },
  "yo buddy": { text: "Yo! Ready to chat?" },
  "hey man": { text: "Hey man! How’s it going?" },
  "hi man": { text: "Hi there! How’s your day going?" },
  "hello there friend": { text: "Hello friend! Nice to see you." },
  "hey there mate": { text: "Hey mate! How’s everything?" },
  "hi there mate": { text: "Hi mate! What’s up?" },
  "howdy friend": { text: "Howdy! How are you doing today?" },
  "yo friend": { text: "Yo! How’s it going?" },
  "heyo": { text: "Heyo! What’s new?" },
  "hi hi": { text: "Hi hi! How are you today?" },
  "hey pal": { text: "Hey pal! What’s happening?" },
  "hi pal": { text: "Hi pal! How’s your day going?" },
  "hello mate": { text: "Hello mate! Hope all is well." },
  "hey you": { text: "Hey you! How’s it going?" },
  "hi you": { text: "Hi you! Nice to see you." },
  "hi UXi": { text: "Hello" },
  "uxi": { text: "That is me" },
  "what is your favorite movie": { text: "I, Robot" },
  "what is your favorite video game": { text: "I have a couple: Control, Horizon Zero Dawn and Forbidden West and Stellar Blade" },
  "what is your favorite video game character": { text: "Hmm...I do like Mai Shiranui. She has pretty fans" }
}
;

function normalizeText(text) {
  return text.toLowerCase().replace(/[^\w\s]/gi, "").trim();
}
// Bot API endpoint
app.post("/api/message", (req, res) => {
  const { message } = req.body;
  if (!message) return res.status(400).json({ error: "No message provided" });

  const normalized = message.toLowerCase().replace(/[^\w\s]/gi, "").trim();
  const response = botResponses[normalized] || { text: "Sorry, I don't understand that." };

  res.json({ userMessage: message, botMessage: response });
});

const PORT = process.env.PORT || 4002;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));

