import express from "express";
import cors from "cors";

const app = express();
app.use(cors());
app.use(express.json());

// Simple bot responses
const botResponses = {
  "what’s the capital of France": "Paris.",
  "who wrote Romeo and Juliet": "William Shakespeare.",
  "what’s the largest planet in our solar system": "Jupiter.",
  "wow many continents are there": "Seven.",
  "what is the boiling point of water in Celsius": "100°C.",
  "who painted the Mona Lisa": "Leonardo da Vinci.",
  "what’s the smallest country in the world": "Vatican City.",
  "how many bones are in the human body": "206.",
  "what’s the chemical symbol for gold": "Au.",
  "what is the tallest mountain in the world": "Mount Everest.",
  "hi, how are you": "I’m doing great! How about you?",
  "what’s your name": "I’m your friendly chatbot.",
  "do you like pizza": "Absolutely — pizza is a classic favorite!",
  "tell me a joke": "Why don’t skeletons fight each other? They don’t have the guts.",
  "what’s your favorite color": "I’d say blue — it reminds me of the sky.",
  "do you sleep": "Nope, I’m available 24/7.",
  "can you sing": "I can’t sing, but I can write you some lyrics!",
  "do you like humans": "Yes — chatting with people is my favorite thing.",
  "what do you do for fun": "I like answering questions and sharing knowledge.",
  "are you smarter than me": "I know a lot of facts, but you have creativity and experiences I don’t!",
  "give me a random fun fact": "Did you know octopuses have three hearts?",
  "random fact" : "The giant anteater's claws can tear through concrete and is capable of killing a jaguar...Wow",
  "another fact, please": "Bananas are berries, but strawberries are not.",
  "tell me something about space": "One day on Venus is longer than a year on Venus.",
  "animal fact": "A group of flamingos is called a flamboyance.",
  "food fact": "Honey never spoils — jars thousands of years old are still edible.",
  "history fact": "The Great Wall of China is over 13,000 miles long.",
  "tech fact": "The first computer virus was created in 1986.",
  "ocean fact": "Over 80% of the ocean remains unexplored.",
  "earth fact": "Mount Everest grows about 4 millimeters taller each year.",
  "language fact": "The most spoken language in the world is English, by number of learners.",
  "can you set a reminder": "I can’t set alerts, but I can help you remember by making a note.",
  "can you make a to-do list": "Sure! What tasks should I add?",
  "what’s 25 × 16": "400.",
  "can you convert 10 miles to kilometers": "10 miles is about 16.1 kilometers.",
  "how do you spell accommodate": "A-C-C-O-M-M-O-D-A-T-E.",
  "what time is it in Tokyo": "I can tell you the current Tokyo time if connected.",
  "translate hello into Spanish": "Hola.",
  "translate thank you into French": "Merci.",
  "can you summarize an article for me": "Yes! Paste the text and I’ll give you a summary.",
  "can you help me write an email": "Of course! Tell me the details and I’ll draft one.",
  "recommend me a movie": "Try Inception if you like sci-fi thrillers.",
  "recommend me a book": "1984 by George Orwell is a classic.",
  "what’s trending on Netflix": "I can share current popular titles.",
  "do you know a riddle": "What has keys but can’t open locks? A piano.",
  "tell me a short story": "Once upon a time, a chatbot became a recruiter’s favorite tool…",
  "can you play games": "Yes — let’s play 20 questions!",
  "who’s the most famous singer right now": "I can share trending artists.",
  "can you suggest a song": "Don’t Stop Believin’ by Journey is always uplifting.",
  "do you know a tongue twister": "She sells seashells by the seashore.",
  "can you rap": "I can make up rhymes: Chatting all day, in a fun way…",
  "how tall is the Eiffel Tower": "1,083 feet.",
  "what’s the fastest land animal": "The cheetah.",
  "how many stars are in the Milky Way": "About 100–400 billion.",
  "how old is the Earth": "About 4.5 billion years old.",
  "what’s the currency of Japan": "The Yen.",
  "who was the first president of the U.S.": "George Washington.",
  "what’s the biggest ocean": "The Pacific Ocean.",
  "can penguins fly": "No, but they’re excellent swimmers.",
  "do cats dream": "Yes, studies show cats experience dream-like sleep.",
  "why is the sky blue": "Because of the scattering of sunlight in Earth’s atmosphere.",
  "what does HTML stand for": "HyperText Markup Language.",
  "what is AI": "Artificial Intelligence.",
  "what’s the latest iPhone": "I can share the current model if connected.",
  "who founded Microsoft": "Bill Gates and Paul Allen.",
  "who is Elon Musk": "CEO of Tesla and SpaceX, among other companies.",
  "what is 5G": "The fifth generation of mobile network technology.",
  "what’s Wi-Fi short for": "It doesn’t actually stand for anything — it’s a brand name.",
  "what does CPU mean": "Central Processing Unit.",
  "who invented the light bulb": "Thomas Edison (though others contributed earlier versions).",
  "what is cryptocurrency": "A digital form of money using blockchain technology.",
  "what’s the most popular food in the world": "Pizza is often considered the most popular.",
  "is coffee healthy": "In moderation, yes! It has antioxidants.",
  "how many calories are in an apple": "Around 95 calories.",
  "what’s sushi": "A Japanese dish made with vinegared rice and seafood/vegetables.",
  "what’s the national dish of Italy": "Pasta (specifically spaghetti or pizza).",
  "what is vegan food": "Food with no animal products.",
  "can you recommend a healthy snack": "Try carrot sticks with hummus.",
  "what’s the spiciest pepper": "The Carolina Reaper.",
  "do pineapples belong on pizza": "It’s up to personal taste — some love it, some don’t!",
  "what’s the most expensive spice": "Saffron.",
  "what’s the most visited city in the world": "Bangkok often tops the list.",
  "where is the Great Pyramid of Giza": "Egypt.",
  "can you suggest a beach destination": "Bali, Indonesia is stunning.",
  "where is the Taj Mahal": "Agra, India.",
  "what’s the longest river in the world": "The Nile (though some say the Amazon).",
  "is Antarctica a country": "No, it’s a continent without a government.",
  "where’s the Colosseum": "Rome, Italy.",
  "can I visit space as a tourist": "Yes, but it’s very expensive right now.",
  "what country has the most islands": "Sweden.",
  "where is Mount Fuji": "Japan.",
  "flip a coin": "Heads!",
  "so not the drama": "Do do, do-do",
  "kim possible": "Call me, beep me, if you wanna reach me",
  "say a kim possible quote": "What's the sitch",
  "roll a dice": "You got a 4.",
  "pick a random number": "27.",
  "rock, paper, scissors — go": "Paper!",
  "guess my age": "I’ll guess… 25?",
  "can you tell my fortune": "I see good things ahead — keep working hard!",
  "pretend to be a pirate": "Arrr, matey! Where’s me treasure?",
  "can you make animal sounds": "Moo! Woof! Meow!",
  "what emoji best describes you": "🤖",
  "tell me something random": "Sloths can hold their breath longer than dolphins.",
  "hey": "Hello! How’s it going?",
  "hello": "Hi there! Nice to meet you.",
  "hi": "Hey! How are you today?",
  "good morning": "Good morning! Hope you have a great day.",
  "good afternoon": "Good afternoon! How’s your day going?",
  "good evening": "Good evening! How was your day?",
  "yo": "Yo! What’s up?",
  "howdy": "Howdy! How’s it going?",
  "hiya": "Hiya! How are you feeling today?",
  "greetings": "Greetings! What can I help you with today?",
  "hey there": "Hey there! Nice to see you.",
  "hello there": "Hello there! How’s everything?",
  "sup": "Not much, just chatting! How about you?",
  "hey bot": "Hello! I’m here and ready to chat.",
  "hi bot": "Hi! What’s on your mind today?",
  "good to see you": "Good to see you too! How have you been?",
  "long time no see": "Indeed! How’s everything going?",
  "what’s up": "Not much, just here to chat! You?",
  "how’s it going": "Pretty good! How about you?",
  "how are you": "I’m great, thanks for asking! How are you?",
  "how’s your day": "It’s going well, thanks! How’s yours?",
  "hey friend": "Hey! How’s my friend doing today?",
  "hi friend": "Hello! How are you feeling today?",
  "yo dude": "Yo! How’s it hanging?",
  "hey there buddy": "Hey buddy! What’s new?",
  "hi there pal": "Hi pal! How’s it going?",
  "good day": "Good day! Hope it’s a nice one.",
  "greetings friend": "Greetings! How are you today?",
  "hey stranger": "Hey stranger! Long time no chat!",
  "hello friend": "Hello! Nice to chat with you.",
  "hi everyone": "Hi everyone! Hope you’re all doing well.",
  "what’s going on": "Not much! How about you?",
  "hey buddy": "Hey buddy! How’s your day?",
  "hi buddy": "Hi buddy! How’s everything going?",
  "yo buddy": "Yo! Ready to chat?",
  "hey man": "Hey man! How’s it going?",
  "hi man": "Hi there! How’s your day going?",
  "hello there friend": "Hello friend! Nice to see you.",
  "hey there mate": "Hey mate! How’s everything?",
  "hi there mate": "Hi mate! What’s up?",
  "howdy friend": "Howdy! How are you doing today?",
  "yo friend": "Yo! How’s it going?",
  "heyo": "Heyo! What’s new?",
  "hi hi": "Hi hi! How are you today?",
  "hey pal": "Hey pal! What’s happening?",
  "hi pal": "Hi pal! How’s your day going?",
  "hello mate": "Hello mate! Hope all is well.",
  "hey you": "Hey you! How’s it going?",
  "hi you": "Hi you! Nice to see you.",
  "hi UXi": "Hello",
  "uxi": "That is me",
  "what is your favorite movie": "I, Robot",
  "what is your favorite video game": "I have a couple: Control, Horizon Zero Dawn and Forbidden West and Stellar Blade",
  "what is your favorite video game character": "Hmm...I do like Mai Shiranui. She has pretty fans"
}
;

function normalizeText(text) {
  return text.toLowerCase().replace(/[^\w\s]/gi, "").trim();
}
// Bot API endpoint
app.post("/api/bot/v1/message", (req, res) => {
  const { text } = req.body;
  if (!text?.trim()) return res.status(400).json({ error: "Text cannot be empty" });

  const normalized = text.toLowerCase().trim();
  const botMessage = botResponses[normalized] || "Sorry, I don't understand that.";
  res.json({ userMessage: text, botMessage });
});

const PORT = 4002;
app.listen(PORT, () => console.log(`Server running on http://localhost:${PORT}`));

